const mockIncidents = [
  {
    id: "INC-1001",
    timestamp: "2026-07-03 10:31:24",
    camera: "Camera 01",
    location: "Main Entrance",
    type: "Fire",
    confidence: 97,
    severity: "High",
    status: "Open",
    thumbnail: null,
  },
  {
    id: "INC-1002",
    timestamp: "2026-07-03 10:26:10",
    camera: "Camera 03",
    location: "Parking Area",
    type: "Crowd",
    confidence: 91,
    severity: "Medium",
    status: "Investigating",
    thumbnail: null,
  },
  {
    id: "INC-1003",
    timestamp: "2026-07-03 10:18:42",
    camera: "Camera 02",
    location: "Library",
    type: "Smoke",
    confidence: 86,
    severity: "High",
    status: "Resolved",
    thumbnail: null,
  },
  {
    id: "INC-1004",
    timestamp: "2026-07-03 10:12:05",
    camera: "Camera 04",
    location: "Administration Block",
    type: "Fire",
    confidence: 94,
    severity: "Critical",
    status: "Open",
    thumbnail: null,
  },
  {
    id: "INC-1005",
    timestamp: "2026-07-03 10:03:51",
    camera: "Camera 05",
    location: "Cafeteria",
    type: "Crowd",
    confidence: 88,
    severity: "Low",
    status: "Resolved",
    thumbnail: null,
  },
];

export default mockIncidents;